services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sistema_achados_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ..:/var/www
    ports:
      - "8300:8000"
    depends_on:
      - db
    command: >
      sh -c "php artisan storage:link --force &&
             chmod -R 775 storage bootstrap/cache &&
             php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: sistema_achados_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistema_achados_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3320:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: